#######################
# Build dev           #
# Name: front_service #
#######################

FROM vitorjordao/nginx-node-npm-yarn:1.0


RUN rm /etc/nginx/conf.d/default.conf

COPY front.conf /etc/nginx/conf.d/

RUN echo Run NGINX 
RUN service nginx start && \
    nginx -t && \
    nginx -s reload
RUN echo End NGINX