#######################
# Build dev           #
# Name: front_service #
#######################

FROM vitorjordao/nginx-node-npm-yarn:1.0

RUN rm /etc/nginx/conf.d/default.conf

COPY . /etc/nginx/

COPY front.conf /etc/nginx/conf.d/

RUN service nginx start && \
    nginx -t && \
    nginx -s reload

CMD cd /etc/nginx/ && \
    yarn && \
    yarn gulp && \
    cd /etc/nginx/Screens/Dashboard/ &&\
    yarn && \
    yarn watch
    